# Generated by Django 3.2.8 on 2023-09-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechayhora', models.CharField(max_length=200, verbose_name='titulo')),
                ('documento', models.FileField(null=True, upload_to='documentos/', verbose_name='documento')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
            ],
        ),
    ]
